name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.SUBMODULE_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build project without tests
        run: ./gradlew clean build -x test

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            PROJECT_DIR=~/MJS_BACKEND
            cd $PROJECT_DIR

            echo "[1] Stop existing server"
            pkill -f 'java -jar' || true
            sleep 2

            echo "[2] Reset local changes"
            git reset --hard HEAD
            git clean -fd

            echo "[3] Pull latest code from origin"
            git pull origin main

            echo "[4] Build project without tests"
            ./gradlew build -x test

            echo "[5] Run latest JAR"
            JAR_PATH=$(ls build/libs/*.jar | head -n 1)
            nohup java -jar $JAR_PATH > nohup.out 2>&1 &
